import { Container, SSRProvider } from "../components/bootstrap";
import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "../components/NavBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextJs Image Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SSRProvider>
          <NavBar />
          <main>
            <Container className="m-5">{children}</Container>
          </main>
        </SSRProvider>
      </body>
    </html>
  );
}
